import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'

const iranSans = localFont({
  src: [
    {
      path: '../../public/fonts/IRANSansXFaNum-Black.woff',
      weight: '900',
      style: 'normal',
    },
    {
      path: '../../public/fonts/IRANSansXFaNum-ExtraBold.woff',
      weight: '800',
      style: 'normal',
    },
    {
      path: '../../public/fonts/IRANSansXFaNum-Bold.woff',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../../public/fonts/IRANSansXFaNum-DemiBold.woff',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../../public/fonts/IRANSansXFaNum-Medium.woff',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../../public/fonts/IRANSansXFaNum-Regular.woff',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/IRANSansXFaNum-Light.woff',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../../public/fonts/IRANSansXFaNum-ExtraBold.woff',
      weight: '200',
      style: 'normal',
    },
    {
      path: '../../public/fonts/IRANSansXFaNum-Thin.woff',
      weight: '100',
      style: 'normal',
    },
  ],
  variable: '--font-iranSans',
  preload: true,
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='fa' dir='rtl'>
      <body className={`${iranSans.className} bg-white`}>{children}</body>
    </html>
  )
}
